// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4caWFTy1edXINHUcl36FJgi_MTLyB9-M',
    appId: '1:450481081257:web:ceb171499821c2aa6112b8',
    messagingSenderId: '450481081257',
    projectId: 'iplexgram',
    authDomain: 'iplexgram.firebaseapp.com',
    storageBucket: 'iplexgram.appspot.com',
    measurementId: 'G-GG87KC0YWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNYsG4tVJPenvQVDuFJp1Ufnq4mBT0psk',
    appId: '1:450481081257:android:da5405d7e0ecdd536112b8',
    messagingSenderId: '450481081257',
    projectId: 'iplexgram',
    storageBucket: 'iplexgram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVUYSn7TkNhjCy8A4RS3c0cyhSBRRRKA',
    appId: '1:450481081257:ios:a1945371033ab5ad6112b8',
    messagingSenderId: '450481081257',
    projectId: 'iplexgram',
    storageBucket: 'iplexgram.appspot.com',
    iosClientId: '450481081257-6qin4itjjl92uj8qbk0d63t4g1ro51km.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmedia',
  );
}
